multifile node/1, nodeName/2, nodeType/2, edge/3, edgeName/2.
dynamic node/1, nodeName/2, nodeType/2, edge/3, edgeName/2.
node('Status').
nodeName('Status','C90').
nodeType('Status','Class').
node('C90').
nodeName('C90','C90').
nodeType('C90','ClsIdx').
node('Activity_status').
nodeName('Activity_status','C32').
nodeType('Activity_status','Class').
node('Equipment').
nodeName('Equipment','C90').
nodeType('Equipment','Class').
node('Activity').
nodeName('Activity','C340').
nodeType('Activity','Class').
node('C32').
nodeName('C32','C32').
nodeType('C32','ClsIdx').
node('9').
nodeName('9','150').
nodeType('9','Arg').
node('3').
nodeName('3','50').
nodeType('3','Arg').
node('5').
nodeName('5','200').
nodeType('5','Arg').
node('6').
nodeName('6','100').
nodeType('6','Arg').
node('X2').
nodeName('X2','X2').
nodeType('X2','Var').
node('X3').
nodeName('X3','X3').
nodeType('X3','Var').
node('C340').
nodeName('C340','C340').
nodeType('C340','ClsIdx').
node('X1').
nodeName('X1','X1').
nodeType('X1','Var').
node('X6').
nodeName('X6','X6').
nodeType('X6','Var').
node('X7').
nodeName('X7','X7').
nodeType('X7','Var').
node('X4').
nodeName('X4','X4').
nodeType('X4','Var').
node('X5').
nodeName('X5','X5').
nodeType('X5','Var').
edge('0','X1','3').
edgeName('0','tk_Type').
edge('1','X2','6').
edgeName('1','tk_ACT').
edge('2','X3','9').
edgeName('2','tk_Status').
edge('3','X1','X2').
edgeName('3','nsubjpass').
edge('4','X4','5').
edgeName('4','tk').
edge('5','X4','X2').
edgeName('5','auxpass').
edge('6','X5','Activity').
edgeName('6','EAT_class_0').
edge('7','X1','X5').
edgeName('7','ont_What_0').
edge('8','X6','Activity_status').
edgeName('8','EAT_class_1').
edge('9','X1','X6').
edgeName('9','ont_What_1').
edge('10','X7','Status').
edgeName('10','EAT_class_2').
edge('11','X1','X7').
edgeName('11','ont_What_2').
edge('12','C340','Activity').
edgeName('12','Class').
edge('13','C90','Status').
edgeName('13','Class').
edge('14','C32','Activity_status').
edgeName('14','Class').
edge('15','C90','Equipment').
edgeName('15','Class').
eat('Activity').
eat('Activity_status').
eat('Status').
involvedVars('X2').
involvedVars('X3').
involvedVars('X1').
involvedVars('X4').
